### ISSUE TITLE
[Error] IndexError: list index out of range

### ISSUE THREAD

**Issue by rbuenger** [menahishayan/HomeScript#3]
getting an index out of range error with my homebridge configuration.

> Traceback (most recent call last):
>   File "./homeScriptO.py", line 40, in getAccessories
>     accessories.update({str(item['services'][1]['characteristics'][0]['value'] or item['services'][0]['characteristics'][2]['value']).replace(' ','_') : {'aid':item['aid'],'iid':item['services'][1]['characteristics'][1]['iid'],'type':item['services'][0]['characteristics'][2]['value'],'value':item['services'][1]['characteristics'][1]['value']}})
> IndexError: list index out of range
> 

got around it by adding another try/except block in getAccessories:

> def getAccessories():
>     global getAcc
>     try:
>         getAcc = requests.get(url + 'accessories', headers=headers)
>         for item in getAcc.json()['accessories']:
>             try:
>                 accessories.update({str(item['services'][1]['characteristics'][0]['value'] or item['services'][0]['characteristics'][2]['value']).replace(' ','_') : {'aid':item['aid'],'iid':item['services'][1]['characteristics'][1]['iid'],'type':item['services'][0]['characteristics'][2]['value'],'value':item['services'][1]['characteristics'][1]['value']}})
>             except:
>                 print '!accessory exception!'
>     except:
>         # print(sys.exc_info()[0])
>         if sys.argv[1] == '-d' or sys.argv[1] == '--debug':
>             # debugHandler(str(sys.exc_info()[0]))
>             logging.error(Exception, exc_info=True)
>             print 'Exception logged: ' + exceptionFile
>     return accessories

[homescript_debug_2020.07.18.log](https://github.com/menahishayan/HomeScript/files/4942257/homescript_debug_2020.07.18.log)
[homescript_exception_2020.07.18.log](https://github.com/menahishayan/HomeScript/files/4942258/homescript_exception_2020.07.18.log)

**Comment by menahishayan** [comment]
Fixed as of v4.1
