### ISSUE TITLE
Feature Request: Brightness Up / Down

### ISSUE THREAD

**Issue by garevans** [menahishayan/HomeScript#7]
I've written a pretty terrible bash script that gets the current brightness and then adjusts it up / down depending on the script I run:

```
#!/bin/bash

CURRENT=$(~/homeScript/homeScript.py -g desk | awk '{print $19}' | tr -d "},")
NEW=$(expr $CURRENT - 10)

~/homeScript/homeScript.py -s desk -b $NEW
```

I was wondering if there was a more elegant way to do this directly with the -b option ? 
My use case in case you're curious is having them mapped to F keys on my keyboard for brightness up / down.

thanks again for a fantastic script :)

**Comment by thaikolja** [comment]
Hi garevans,

I'm so sorry for going off-topic, but I couldn't find another way to contact you. Would you be interested in collaborating in Dropzone 4 actions on a newly created GitLab group? The goal is to write quality actions. You'd have the Maintainer role.

https://gitlab.com/dropzone-actions

If yes, please send your email address or GitLab username to kolja.nolte@gmail.com

**Comment by menahishayan** [comment]
> I was wondering if there was a more elegant way to do this directly with the -b option

I hear you! With **v5.2 I've specifically built this feature in.**

`hs.py -s desk -b +10`

Its that simple!

Unfortunately, I don't have any devices that support brightness control so I can't know for sure if it's working unless someone can test it out for me. Let me know if you run into any issues.

> thanks again for a fantastic script :)

Thank you for your support! Always a pleasure contributing to the open source community. If you'd like to contribute to this project, or any of my other projects, you can make a small donation via the links :)
